# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90ffeb4f6f07838f1c08b2eb25a5cb39628d6a4d4ecdf928aeaef1c70d917a34a0898626b128eae1ce14566f0d3cef387085278ceb62283ed813d2c7faa08bdc

test:
  secret_key_base: 065e08786c0cbefa1ae45d0bff117884b44ba16b5ef32f768d45bc4a7016f1b541fed49341c00f5efd60bc467b9e15651cb0c470e1aaf106c90c0724290d2a48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
